version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current-22.04
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to dockerhub and export environment variables
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
            echo 'export IMAGE_NAME="philbug/revanced-builder"' >> $BASH_ENV
            echo 'export FILE_PATH="revanced"' >> $BASH_ENV

      - run:
          name: Clone application repository and get newest tag
          command: |
            git clone https://github.com/reisxd/revanced-builder.git $FILE_PATH
            cd $FILE_PATH
            git fetch --tags
            rev="$(git rev-list --tags --max-count=1)"
            echo "export LATEST_TAG=$(git describe --tags $rev)" >> $BASH_ENV

      - run:
          name: Build image
          command: |
            echo "Building version $DOCKER_TAG"

            git -C $FILE_PATH checkout $LATEST_TAG
            cp Dockerfile .dockerignore $FILE_PATH

            docker build -f $FILE_PATH/Dockerfile \
              -t $IMAGE_NAME:$(echo $LATEST_TAG | tr -d 'v') \
              -t $IMAGE_NAME:latest $FILE_PATH

      - run:
          name: Push image
          command: |
            docker push $IMAGE_NAME:$(echo $LATEST_TAG | tr -d 'v')
            docker push $IMAGE_NAME:latest
